### ISSUE TITLE
Add "Copy Signed Message" button

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion-Wallet#14]
Right now after you sign a message within the wallet it is displayed as text that must be highlighted and copied.  Almost all situations where you would want to manually sign a message will also involve you copying it away from the wallet to use it somewhere else.  

Please add a "Copy to clipboard" button when you display signed messages.

**Comment by loon3** [comment]
Sign & Copy button added in v0.3.0
