### ISSUE TITLE
Wallet should detect and display unconfirmed incoming transactions

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion-Wallet#15]
Counterwallet does this and it would be nice if the LTB Companion could provide this information

Here's an idea of how it could look
![image](https://cloud.githubusercontent.com/assets/6858319/7310817/898b33d2-e9e7-11e4-81c3-0a453def345c.png)

**Comment by loon3** [comment]
I hope to piggy back this off the work @deweller is doing with xchain to parse unconfirmed counterparty txs

**Comment by loon3** [comment]
Short term fix for this is displaying unconfirmed transactions on chain.so, v0.4.1, will re-visit once xchain api is available
