### ISSUE TITLE
Don't black out the password when it is typed during the initial "I have a counterwallet phrase" step

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion-Wallet#16]
Had a user who can't touch-type mess up wallet recovery because they couldnt see what they were typing.  This was easily noted and fixed in the "view wallet passphrase" menu and was easily re-entered through the manual re-entry, so the problem seems to be the viewing restriction during initial wallet setup.

**Comment by loon3** [comment]
Noted, I just updated the field type and will push it through with the next version.  I'll leave this issue open until the next version is released.

**Comment by loon3** [comment]
fixed in v0.3.0
