### ISSUE TITLE
send-to-ltb username is capitalization sensitive, it should not be

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion-Wallet#17]
Users in the LTB system can't register a name that differs from another username only in capitalization so it doesn't make sense for the wallet to force users to correctly capitalize usernames in order to send to them.

Change requested: Make capitalization irrelevant when searching usernames

**Comment by loon3** [comment]
This should not be the case.  The string is converted to lowercase to match the slug which identifies the user profile @ Line 750 of popup.js

```
var userid = $("#sendtoaddress").val().toLowerCase();
```

I just tested it and it appears to be working fine regardless of how the username is capitalized.
