### ISSUE TITLE
Weirdness when trying to send an asset

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion-Wallet#20]
![image](https://cloud.githubusercontent.com/assets/6858319/7328535/2d5bdb80-ea8b-11e4-9450-7401bf7fc390.png)

Transactions are showing up but they're not being deducted from the wallet so I can make multiple transactions that are essentially double spends.  Oddly, none of the spends were detected by xchain or the soupbot

**Comment by loon3** [comment]
did you wait until they were confirmed before making another send?

**Comment by AdamBLevine** [comment]
No, I didn't - But Swapbot usually recognizes unconfirmed transactions
pretty immediately and it hasn't recognized either of these transactions,
one of which eventually confirmed.

It would be much better from a usability standpoint if when you make a send
it automatically refreshes the wallet and the balance takes into account
unconfirmed transactions, so your balance is a reflection of what you want
it to be rather than what the network has confirmed.

If the transaction winds up being rejected your balance would update and
you'd be able to spend it again.

**Comment by loon3** [comment]
Can you send me the tx ids for those specific txs?

There are issues related to storing tx data locally to account for unconfirmed txs.  I'm planning on waiting until I have an API that I can reference to display unconfirmed amounts.  In the meantime, you can never send more than you have, and the transactions will simply be processed in the order they are sent.

**Comment by AdamBLevine** [comment]
Tx_Index    Block   Time (UTC)  Source  Destination
11641895    353543  2015-04-24 21:17:21 177b6SvXUZQTxmgESFdUU3KAXpHG7N1iDn   Send (1KUsjZKrkd7LYRV7pbnNJtofsq1HAiz6MF received 0 SOUP)
11641894    353543  2015-04-24 21:17:21 177b6SvXUZQTxmgESFdUU3KAXpHG7N1iDn   Send (1KUsjZKrkd7LYRV7pbnNJtofsq1HAiz6MF received 6 SOUP)

**Comment by loon3** [comment]
Looks like it did exactly what it was supposed to, since there were 0 SOUP left after the first transaction of 6 SOUP was parsed the second one reverted to 0.

**Comment by loon3** [comment]
related to https://github.com/loon3/LTB-Companion-Wallet/issues/15
