### ISSUE TITLE
In the LTBn Directory pressing "enter" after typing your search string does not initiate the search, you need to click the button. 

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion-Wallet#24]
Title says it all, conclusion is please make it so pressing enter when the search window of the directory is selected causes the search to start.

**Comment by loon3** [comment]
added https://github.com/loon3/LTB-Companion-Wallet/commit/de18a3cbc59bc8f9790c9cd844a72d4faf49ba75

**Comment by AdamBLevine** [comment]
woot!  feels great joe
