### ISSUE TITLE
Apostrophes in tip button labels break display

### ISSUE THREAD

**Issue by cryptonaut420** [loon3/LTB-Companion-Wallet#29]
for instance clicking on the LTB Companion tip button on here: https://letstalkbitcoin.com/blog/post/lets-talk-bitcoin-212-hypercapitalsm-and-the-austrian-approach

When the "Send tokens" page comes up, the label/title it is supposed to display should be the blog post title, but the apostrophe in "Let's talk..." is breaking it, so it only shows "Let".

**Comment by loon3** [comment]
looks like the encodeURIComponent() function doesn't escape all characters

fixed https://github.com/loon3/LTB-Companion-Wallet/commit/eb51e8d423aa1c0907b918be08b468e09cac286c
