### ISSUE TITLE
Searchable LTB user directory

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion-Wallet#4]
Since users will soon be able to send tokens to each other by LTB username it makes sense to let them find those usernames as easily as possible.  Each user in the LTB system has the ability to determine what of their information is public and private.

The wallet should let you search by name, partial username, email or bitcoin public key.

Users should be able to mark users as "favorites" to put them into an auto-completion list that will be one of the possible guesses when you start writing a message or sending a transaction to a name.

**Comment by loon3** [comment]
@cryptonaut420 to add first characters parameter to user list API for search by partial username

**Comment by cryptonaut420** [comment]
@loon3 you can now search for users using /api/v1/users?search=[first letters]

**Comment by loon3** [comment]
added LTBn Directory in v0.3.1

**Comment by loon3** [comment]
additional features discussed here... https://github.com/loon3/LTB-Companion-Wallet/issues/25
