### ISSUE TITLE
Send tokens by LTB Username

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion-Wallet#5]
In the LTB ecosystem users can choose to keep both Bitcoin and Counterparty compatible addresses on file associated with their accounts.  This information can be made private or public, and what is public is available via API.

As discussed it would be great to let users who have addresses on file simply give out their username and let the wallet know which address to send it to.   

Note that there are two types of addresses, counterparty compatible and bitcoin standard - The implementation should differentiate and not allow users to send counterparty tokens to an address that will not be able to understand them.

**Comment by loon3** [comment]
send to username added in v0.2.0, https://github.com/loon3/LTB-Companion-Wallet/commit/b4e584e

uses ltbcoin-address field from letstalkbitcoin.com user public API to ensure counterwallet compatibility

**Comment by AdamBLevine** [comment]
Love the way it changes the username to the bitcoin address right before your eyes
