### ISSUE TITLE
Standardize "asset" terminology" to "token"

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion-Wallet#7]
I know this is non-canonical from what Counterparty calls things in counterwallet but I think we are much better served having users think and speak about these things as tokens which is a very neutral word compared to assets which is a very financialized word.

Basically you'd just need to change it in the creating an asset interface you've yet to create and where it says asset history.

**Comment by loon3** [comment]
Updated all asset references to token in v0.3.1
