### ISSUE TITLE
Integrate Shapeshift "Shifty" button allowing users to convert altcoins into bitcoin without using an exchange

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion-Wallet#9]
https://github.com/Shapeshift-Public/Shifty

If we integrate this, users would be able to easily convert any type of non-bitcoin cryptocurrency supported by Shapeshift into bitcoin in their wallet without using an exchange, which would be great.  

This would make it much easier for non-bitcoin value to come into the bitcoin and thus counterparty/ltbcoin compatible ecosystem.   There is some risk here because shapeshift is a centralized company but given the conversions are nearly instant in the event of a collapse only those trading right at that moment would be impacted.

**Comment by AdamBLevine** [comment]
And awesome, they have an affiliate program so if users get use out of this it's another revenue stream for the project

https://shapeshift.io/affiliate.html

**Comment by loon3** [comment]
added to Apps section in v0.3.0
